### ISSUE TITLE
why ggwithinstats can show the between group p value?

### ISSUE THREAD

**Issue by LiXingguangBrandonStark** [IndrajeetPatil/ggstatsplot_slides#5]

**Comment by IndrajeetPatil** [comment]
What do you mean by "between group p value"?

**Comment by IndrajeetPatil** [comment]
See this to understand which statistical analyses are carried out:
https://indrajeetpatil.github.io/ggstatsplot/articles/web_only/ggwithinstats.html#summary-of-tests

The p-value in that plot is from Fischer's one-way repeated measures ANOVA.

**Comment by LiXingguangBrandonStark** [comment]
<img width="1332" alt="image" src="https://user-images.githubusercontent.com/46078579/168513879-b6498d8d-3a04-4669-bfcb-14b5f99712fd.png">
these p values are between groups, right?

**Comment by LiXingguangBrandonStark** [comment]
but you use ggwithinstats, right?
